version: "2.1"
services:

  ms-html-to-pdfa:
    container_name: ms-html-to-pdfa
    image: ${HTML_TO_PDF_IMAGE}
    networks:
      - api
    expose:
      - 6677
    ports:
      - 6677:6677

  pdf-tests:
    image: ${MAVEN_IMAGE}
    environment:
      - SETTINGS_FILE=${MVN_SETTINGS_FILE_SAAS}
    entrypoint: /bin/bash -c
    networks:
      - api
    command:
      - |
        sleep 10 # so that the kms key can be seeded 
        mvn -Dtest=uk.gov.dwp.health.fitnote.generator.integration.RunCukesTest ${MVN_OPTS} test
    working_dir: /usr/src
    volumes:
      - .:/usr/src
      - ${MVN_M2}:/root/.m2
      - ${MVN_SETTINGS_FILE_SAAS}:/root/.m2/settings.xml

networks:
  api:
