version: "2.1"
services:

  ms-html-to-pdfa:
    image: nexus.service.health-dev.dwpcloud.uk:5000/shared/ms-html-to-pdfa:branch-develop
    networks:
      - api
    expose:
      - 6677
    ports:
      - 6677:6677

  pdf-tests:
    image: ${MAVEN_IMAGE}
    entrypoint: /bin/bash -c
    networks:
      - api
    command:
      - |
        sleep 10 # so that the kms key can be seeded 
        mvn -Dtest=uk.gov.dwp.health.fitnote.generator.integration.RunCukesTest ${MVN_OPTS} test
    working_dir: /usr/src
    volumes:
      - .:/usr/src
      - ${MVN_M2}:/root/.m2
      - ${MVN_SETTINGS_FILE}:/root/.m2/settings.xml

networks:
  api:
