########################################################################################
###   Pipeline configuration using 'workflow' - variables for each pipeline to be    ###
###   set in the relevant condition                                                  ###
########################################################################################

workflow:
  rules:
    ####################################################################################
    ### SEC-DEV Pipeline Execution Policy                                            ###
    ####################################################################################
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"
      when: never
    ####################################################################################
    ### [skip ci]                                                                    ###
    ####################################################################################
    - if: '$CI_COMMIT_MESSAGE =~ /\[skip ci\]/ && $CI_PIPELINE_SOURCE != "schedule" && $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH'
      when: never
    ####################################################################################
    ### FEATURE BRANCHES                                                             ###
    ####################################################################################
    - if: '$CI_COMMIT_REF_NAME =~ /^[Ff]-.*$/ && $CI_PIPELINE_SOURCE != "schedule"'
      changes:
        compare_to: refs/heads/develop
        paths: ['**/*']
      when: always
    ####################################################################################
    ### RELEASE BRANCHES - NONPROD CREDS                                             ###
    ####################################################################################
    - if: '$CI_COMMIT_REF_NAME =~ /^[Rr]-.*$/ && $CI_PIPELINE_SOURCE =~ /^(api|web|push)$/ && $CI_PIPELINE_SOURCE != "schedule" && $CR_NO == null'
      variables:
        ENVIRONMENT: 'nonprodacct'
        # job triggers
        VERSION: "true"
        OPEN_SOURCE: "true"
      when: always
    ####################################################################################
    ### RELEASE BRANCHES - PROD CREDS                                                ###
    ####################################################################################
    - if: '$CI_COMMIT_REF_NAME =~ /^[Rr]-.*$/ && $CI_PIPELINE_SOURCE =~ /^(api|web)$/ && $CR_NO != null'
      variables:
        # job triggers
        VERSION: "true"
        PROD_RELEASE: "true"
        #OIDC Config
        ASSUME_ROLE_NAME: "$PRODUCT-build-prod"
        OPEN_SOURCE: "true"
      when: always
    ####################################################################################
    ### NIGHTLY BUILD SCHEDULE                                                       ###
    ####################################################################################
    - if: '$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "schedule"'
      variables:
        # job triggers
        DOCUMENTATION: "true"
      when: always
    ####################################################################################
    ### MERGE TO DEVELOP                                                             ###
    ####################################################################################
    - if: '$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"' # the only push to default branch is on merge
      variables:
        # job triggers
        MERGE_TO_DEVELOP: "true"
        DOCUMENTATION: "true"
      when: always
    - when: never
