########################################################################################
###    Jobs to open source project                                                   ###
########################################################################################

### ENVIRONMENT
.environment: &environment
  environment:
    name: "$ENVIRONMENT"
    action: prepare

### TRIGGERS
.open-source: &open-source
  rules:
    - if: $OPEN_SOURCE == "true"
      when: manual

open-source:
  extends: .open-source-template
  allow_failure: true
  <<: *environment
  <<: *open-source